// Copyright 2021 Isaac Diamond
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: or_set.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ORSet struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Elements that were added to the set.
	Added []*ORSet_Element `protobuf:"bytes,1,rep,name=Added,proto3" json:"Added,omitempty"`
	// Elements that were added to the set.
	Removed []*ORSet_Element `protobuf:"bytes,2,rep,name=Removed,proto3" json:"Removed,omitempty"`
}

func (x *ORSet) Reset() {
	*x = ORSet{}
	if protoimpl.UnsafeEnabled {
		mi := &file_or_set_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ORSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORSet) ProtoMessage() {}

func (x *ORSet) ProtoReflect() protoreflect.Message {
	mi := &file_or_set_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORSet.ProtoReflect.Descriptor instead.
func (*ORSet) Descriptor() ([]byte, []int) {
	return file_or_set_proto_rawDescGZIP(), []int{0}
}

func (x *ORSet) GetAdded() []*ORSet_Element {
	if x != nil {
		return x.Added
	}
	return nil
}

func (x *ORSet) GetRemoved() []*ORSet_Element {
	if x != nil {
		return x.Removed
	}
	return nil
}

type ORSet_Element struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Value of the element
	Value *anypb.Any `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Unique identifier for this element
	Identifier string `protobuf:"bytes,2,opt,name=identifier,proto3" json:"identifier,omitempty"`
}

func (x *ORSet_Element) Reset() {
	*x = ORSet_Element{}
	if protoimpl.UnsafeEnabled {
		mi := &file_or_set_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ORSet_Element) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ORSet_Element) ProtoMessage() {}

func (x *ORSet_Element) ProtoReflect() protoreflect.Message {
	mi := &file_or_set_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ORSet_Element.ProtoReflect.Descriptor instead.
func (*ORSet_Element) Descriptor() ([]byte, []int) {
	return file_or_set_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ORSet_Element) GetValue() *anypb.Any {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ORSet_Element) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

var File_or_set_proto protoreflect.FileDescriptor

var file_or_set_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6f, 0x72, 0x5f, 0x73, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x70, 0x62, 0x5f, 0x63, 0x72, 0x64, 0x74, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x05, 0x4f, 0x52, 0x53, 0x65, 0x74, 0x12,
	0x2f, 0x0a, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x70, 0x62, 0x5f, 0x63, 0x72, 0x64, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x52, 0x53, 0x65,
	0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x12, 0x33, 0x0a, 0x07, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x64, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x70, 0x62, 0x5f, 0x63, 0x72, 0x64, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x4f,
	0x52, 0x53, 0x65, 0x74, 0x2e, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x52, 0x65,
	0x6d, 0x6f, 0x76, 0x65, 0x64, 0x1a, 0x55, 0x0a, 0x07, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x2a, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x0a,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69, 0x65, 0x72, 0x42, 0x25, 0x5a, 0x23,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x73, 0x61, 0x61, 0x63,
	0x64, 0x39, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x63, 0x72, 0x64, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_or_set_proto_rawDescOnce sync.Once
	file_or_set_proto_rawDescData = file_or_set_proto_rawDesc
)

func file_or_set_proto_rawDescGZIP() []byte {
	file_or_set_proto_rawDescOnce.Do(func() {
		file_or_set_proto_rawDescData = protoimpl.X.CompressGZIP(file_or_set_proto_rawDescData)
	})
	return file_or_set_proto_rawDescData
}

var file_or_set_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_or_set_proto_goTypes = []interface{}{
	(*ORSet)(nil),         // 0: pb_crdt.v1.ORSet
	(*ORSet_Element)(nil), // 1: pb_crdt.v1.ORSet.Element
	(*anypb.Any)(nil),     // 2: google.protobuf.Any
}
var file_or_set_proto_depIdxs = []int32{
	1, // 0: pb_crdt.v1.ORSet.Added:type_name -> pb_crdt.v1.ORSet.Element
	1, // 1: pb_crdt.v1.ORSet.Removed:type_name -> pb_crdt.v1.ORSet.Element
	2, // 2: pb_crdt.v1.ORSet.Element.value:type_name -> google.protobuf.Any
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_or_set_proto_init() }
func file_or_set_proto_init() {
	if File_or_set_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_or_set_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ORSet); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_or_set_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ORSet_Element); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_or_set_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_or_set_proto_goTypes,
		DependencyIndexes: file_or_set_proto_depIdxs,
		MessageInfos:      file_or_set_proto_msgTypes,
	}.Build()
	File_or_set_proto = out.File
	file_or_set_proto_rawDesc = nil
	file_or_set_proto_goTypes = nil
	file_or_set_proto_depIdxs = nil
}
